### ISSUE TITLE
Grammar locations

### ISSUE THREAD

**Issue by okapia** [danielshahaf/parseable-dash-dash-help#1]
This is a minor nit but the normal Unix conventions would be to have all the grammars in a fixed location. So instead of /usr/share/rsync/rsync.grammar, it would be something like
  /usr/share/cli-grammar/rsync

That'd also allow an environment variable to list where to find them.

Okay, it might need a catchy name and there might be a file extension. Not sure if you were planning yaml, json, xml or something custom?

**Comment by danielshahaf** [comment]
> This is a minor nit but the normal Unix conventions would be to have all the grammars in a fixed location. So instead of /usr/share/rsync/rsync.grammar, it would be something like
> /usr/share/cli-grammar/rsync

Fixed.

> That'd also allow an environment variable to list where to find them.

Right, some sort of $CLI_GRAMMAR_PATH envvar with the same syntax as $PATH.

> Okay, it might need a catchy name and there might be a file extension. Not sure if you were planning yaml, json, xml or something custom?

How about "grammy" for the name?  I went ahead and grabbed https://github.com/grammy-org/, hopefully the music people won't try to seize it.

Re file format: I intentionally haven't given that any thought yet.  I was thinking the first task would be to write up what features the file format should _have_.  Only later will deciding on a particular encoding come up.  That is: data model before data encoding.  I now filed this as #2.

Thanks for your input!
